name: TagBot
on:
  repository_dispatch: # I don't know what this is...but maybe one day I can duplicate what the HolyLab does?
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          registry: drbergman/PCVCTRegistry
          lookback: 10
